language: c++ 
before_install:
  - sudo apt-get update -q
#compiler: gcc g++
sudo: true
# install:
#  - libxrandr
#  - libwrandr
dist: bionic
os: linux 
env: 
  - COMPILER_NAME=gcc CXX=g++ CC=gcc
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_DISCORD
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_DISCORD
addons:
  apt:
    packages:
      - libxrandr-dev
      - libopenal-dev
      - libudev-dev
      - libflac-dev
      - libvorbis-dev
      - libogg-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev
      - build-essential
      #- libtinyxml2-dev
      #- libsdl2-dev
      #- libsdl2-net-dev
      #- libfreetype6-dev
      - git
    sources: &sources
      - ubuntu-toolchain-r-test
script:
  - mkdir build
  - cd build
  #- export PATH=$TRAVIS_BUILD_DIR/tools/vcpkg:$PATH
  - cmake -DTOOLCHAIN_FILE=toolchain/linux/Linux_GCC.cmake -DUSE_GLM=ON -DGL_RENDERER=ON -DVCPKG_INSTALLER=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . -- -j4
