dos2unix LICENSE
dos2unix game/include/Client/Client.hpp
dos2unix game/include/Server/Server.hpp
dos2unix game/src/Client/Client.cpp
dos2unix game/src/Commands.cpp
dos2unix game/src/ScriptObjects/ScriptObjectClient.cpp
dos2unix game/src/Server/Server.cpp
dos2unix game/src/UI/stdafx.h
dos2unix include/private/BlackBox/Input/BaseInput.hpp
dos2unix include/private/BlackBox/Renderer/OpenGL/Core.hpp
dos2unix include/private/BlackBox/Renderer/Render.hpp
dos2unix include/private/BlackBox/ScriptSystem/ScriptObject.hpp
dos2unix include/private/BlackBox/ScriptSystem/_ScriptableEx.hpp
dos2unix include/private/BlackBox/System/Console.hpp
dos2unix include/private/BlackBox/System/HardwareMouse.hpp
dos2unix include/private/BlackBox/System/MiniGUI/MiniGUI.cpp
dos2unix include/private/BlackBox/System/NullLog.hpp
dos2unix include/private/BlackBox/System/System.hpp
dos2unix include/public/BlackBox/3DEngine/CryHeaders.h
dos2unix include/public/BlackBox/3DEngine/I3DEngine.hpp
dos2unix include/public/BlackBox/3DEngine/IBindable.hpp
dos2unix include/public/BlackBox/Core/Math/Cry_Camera.h
dos2unix include/public/BlackBox/Core/Math/Cry_Color4.h
dos2unix include/public/BlackBox/Core/Math/Cry_Geo.h
dos2unix include/public/BlackBox/Core/Math/Cry_GeoIntersect.h
dos2unix include/public/BlackBox/Core/Math/Cry_GeoOverlap.h
dos2unix include/public/BlackBox/Core/Math/Cry_Math.h
dos2unix include/public/BlackBox/Core/Math/Cry_Matrix.h
dos2unix include/public/BlackBox/Core/Math/Cry_Quat.h
dos2unix include/public/BlackBox/Core/Math/Cry_Vector3.h
dos2unix include/public/BlackBox/Core/Math/Cry_XOptimise.h
dos2unix include/public/BlackBox/Core/Platform/CryLibrary.h
dos2unix include/public/BlackBox/Core/Platform/Linux_Win32Wrapper.h
dos2unix include/public/BlackBox/Core/Platform/platform_impl.inl
dos2unix include/public/BlackBox/Core/Primitives.hpp
dos2unix include/public/BlackBox/Core/Stream.hpp
dos2unix include/public/BlackBox/Core/StringUtils.h
dos2unix include/public/BlackBox/Core/Tarray.h
dos2unix include/public/BlackBox/EntitySystem/IEntitySystem.hpp
dos2unix include/public/BlackBox/Input/IInput.hpp
dos2unix include/public/BlackBox/Network/INetwork.hpp
dos2unix include/public/BlackBox/Network/Socks_posix.hpp
dos2unix include/public/BlackBox/Network/Socks_win32.hpp
dos2unix include/public/BlackBox/Profiler/Tgaloader.h
dos2unix include/public/BlackBox/Renderer/IFont.hpp
dos2unix include/public/BlackBox/Renderer/IRender.hpp
dos2unix include/public/BlackBox/Renderer/VertexFormats.hpp
dos2unix include/public/BlackBox/ScriptSystem/IScriptSystem.hpp
dos2unix include/public/BlackBox/ScriptSystem/ScriptObject.hpp
dos2unix include/public/BlackBox/ScriptSystem/_ScriptableEx.hpp
dos2unix include/public/BlackBox/System/ConsoleRegistration.h
dos2unix include/public/BlackBox/System/File/ICryPak.hpp
dos2unix include/public/BlackBox/System/IConsole.hpp
dos2unix include/public/BlackBox/System/ISystem.hpp
dos2unix include/public/BlackBox/Threading/IThreadManager.h
dos2unix include/public/BlackBox/Utils/smartptr.hpp
dos2unix src/Engine/3DEngine/CGF/CgfDump.cpp
dos2unix src/Engine/3DEngine/CGF/CgfUtils.cpp
dos2unix src/Engine/3DEngine/CGF/CryHeaders.h
dos2unix src/Engine/3DEngine/Scene/SceneSerialization.cpp
dos2unix src/Engine/GUI/GuiTools/ImGuiFileBrowser/imfilebrowser.h
dos2unix src/Engine/GUI/ImGuiBackend/Vanila/imgui_impl_opengl3.cpp
dos2unix src/Engine/GUI/ImGuiBackend/Vanila/imgui_impl_sdl.cpp
dos2unix src/Engine/GUI/ImGuiBackend/Vanila/imgui_impl_sdl.h
dos2unix src/Engine/GUI/ImGuiInput.cpp
dos2unix src/Engine/GUI/ImGuiManager.cpp
dos2unix src/Engine/GUI/ImGuiRenderer.cpp
dos2unix src/Engine/GUI/MemoryEditor.h
dos2unix src/Engine/GUI/imgui.cpp
dos2unix src/Engine/GUI/imgui.h
dos2unix src/Engine/GUI/imgui_demo.cpp
dos2unix src/Engine/GUI/imgui_draw.cpp
dos2unix src/Engine/GUI/imgui_impl_sdl.cpp
dos2unix src/Engine/GUI/imgui_internal.h
dos2unix src/Engine/GUI/imgui_widgets.cpp
dos2unix src/Engine/GUI/imstb_rectpack.h
dos2unix src/Engine/GUI/imstb_textedit.h
dos2unix src/Engine/GUI/imstb_true.h
dos2unix src/Engine/GUI/imstb_truetype.h
dos2unix src/Engine/Input/BaseInput.cpp
dos2unix src/Engine/Input/SDLKeyboard.cpp
dos2unix src/Engine/Input/SDLMouse.cpp
dos2unix src/Engine/Input/SDLPad.cpp
dos2unix src/Engine/Profiler/Profiler.cpp
dos2unix src/Engine/Profiler/Tgaloader.cpp
dos2unix src/Engine/Renderer/BaseShader.cpp
dos2unix src/Engine/Renderer/BaseShaderLoading.cpp
dos2unix src/Engine/Renderer/HdrTechnique.cpp
dos2unix src/Engine/Renderer/OpenGL/GLRenderer.cpp
dos2unix src/Engine/Renderer/Shaders/FxParser.cpp
dos2unix src/Engine/Renderer/Shaders/FxParser.h
dos2unix src/Engine/Renderer/Shaders/Parser.yy
dos2unix src/Engine/Renderer/Shaders/Scanner.cpp
dos2unix src/Engine/Renderer/Shaders/Scanner.ll
dos2unix src/Engine/Renderer/Shaders/driver.hpp
dos2unix src/Engine/Renderer/parser.hh
dos2unix src/Engine/ScriptSystem/LuaDebugger/LUADBG.cpp
dos2unix src/Engine/ScriptSystem/LuaDebugger/LUADBG.h
dos2unix src/Engine/ScriptSystem/LuaDebugger/_TinyWindow.h
dos2unix src/Engine/ScriptSystem/ScriptObject.cpp
dos2unix src/Engine/ScriptSystem/ScriptSystem.cpp
dos2unix src/Engine/ScriptSystem/StdAfx.h
dos2unix src/Engine/System/Console.cpp
dos2unix src/Engine/System/HardwareMouse.cpp
dos2unix src/Engine/System/NullLog.cpp
dos2unix src/Engine/System/RemoteConsole/RemoteConsole.h
dos2unix src/Engine/System/System.cpp
dos2unix src/Engine/System/SystemInit.cpp
dos2unix src/Engine/System/SystemThreading.cpp
dos2unix src/Engine/System/SystemThreading.h
dos2unix src/Engine/System/Timer.cpp
dos2unix src/Engine/System/WindowsConsole.cpp
dos2unix src/Engine/System/WindowsConsole.h
dos2unix src/Engine/System/XConsoleVariable.cpp
dos2unix src/Engine/System/XConsoleVariable.h
dos2unix src/Engine/Window/SDLWindow.cpp
dos2unix src/Engine/Window/_TinyWindow.hpp
