set(LAUNCHER_DIR)
if (OPTION_ENGINE)
	if (NOT ANDROID)
		set(OPTION_LAUNCHER_EXECUTABLE "GameLauncher" CACHE STRING "Base file name for the game executable (without file extension)")
	endif()
	if (ANDROID)
		add_subdirectory("Code/Launcher/AndroidLauncher")
	elseif (LINUX)
		add_subdirectory("Code/Launcher/LinuxLauncher")
	elseif (WINDOWS)
		add_subdirectory("Code/Launcher/DedicatedLauncher")
		add_subdirectory("Code/Launcher/WindowsLauncher")
	endif ()
endif()

#set_solution_startup_target(Launcher)
#set_property(TARGET Launcher PROPERTY VS_DEBUGGER_WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
