function(PrepareVcpkg)
	if (NOT (IS_DIRECTORY ${CMAKE_SOURCE_DIR}/vcpkg/.git))
		message(STATUS "----------------------Download vcpkg")
		set(CMD git clone https://github.com/microsoft/vcpkg.git ${CMAKE_SOURCE_DIR}/vcpkg)
		execute_process(COMMAND ${CMD} RESULT_VARIABLE RESULT)

		if (NOT RESULT EQUAL 0)
			message(FATAL_ERROR "Could not download vcpkg")
		endif()
	endif()
	if(NOT (EXISTS ${CMAKE_SOURCE_DIR}/vcpkg/vcpkg OR ${CMAKE_SOURCE_DIR}/vcpkg/vcpkg.exe))
		message(STATUS "Compiling vcpkg")
    set(FEXT bat)
    if (LINUX)
      set(FEXT sh)
    endif()
    execute_process(COMMAND ${CMAKE_SOURCE_DIR}/vcpkg/bootstrap-vcpkg.sh WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/vcpkg RESULT_VARIABLE RESULT)
		if (NOT RESULT EQUAL 0)
			message(FATAL_ERROR "Could not compile vcpkg")
		endif()
	endif()
endfunction()

