name: CMake on a single platform

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    # - name: Install dependencies with vcpkg
    #   run: |
    #     ./vcpkg/vcpkg install --triplet x64-windows

    - name: Cache Cygwin, cyg-get, Flex, and Bison
      id: cache-cygwin
      uses: actions/cache@v2
      with:
        path: C:\cygwin64\bin
        key: ${{ runner.os }}-cygwin-cygget-flex-bison-${{ hashFiles('**/flex-bison-version.txt') }}
        restore-keys: |
          ${{ runner.os }}-cygwin-cygget-flex-bison-

    - name: Install Cygwin and tools
      if: steps.cache-cygwin.outputs.cache-hit != 'true'
      run: |
        choco install cygwin --params "/InstallDir:C:\cygwin64"
        choco install cyg-get -y
        cyg-get install flex bison

    - name: Add Cygwin to PATH
      run: echo "C:\cygwin64\bin" >> $env:GITHUB_PATH

    - name: Configure CMake
      run: cmake --preset vs2022-msvc
      
    - name: Build (Debug)
      run: cmake --build --preset vs2022 --config Debug

    - name: Build (Release)
      run: cmake --build --preset vs2022 --config Release

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}

